#!/bin/sh -efu

. shell-error
. uevent-sh-functions

case "${1-}" in
	''|-h|--help)
		printf 'Usage: %s <KEY> <CONTENT>...'
		exit 0
		;;
esac

key="$1"; shift

[ "$#" != 0 ] ||
	fatal "more argumets required"

event="$(make_event)"
printf '%s\n' "$@" > "$event"
release_event "$key" "$event"
