#!/bin/sh
### BEGIN INIT INFO
# Provides:            uevent
# Required-Start:      cmdline fstab mountvirtfs
# Should-Start:        $syslog udev
# Required-Stop:
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:
# Short-Description:   Process kernel events.
# Description:         Processing kernel events.
### END INIT INFO

. /etc/init.d/template
. uevent-sh-functions

NAME=ueventd
PIDFILE=/var/run/$NAME.pid
ARGS="--lockfile $LOCKFILE --pidfile $PIDFILE"

prepare() {
	mkdir -p -- \
		"$eventdir/periodic" \
		"$eventdir/udev" \
		"$handlerdir" \
	#
	:>"$eventdir/periodic/.dirty"
}

start() {
	prepare
	start_daemon $ARGS -- \
		"$NAME" \
		    ${RDUEVENT_TIMEOUT:+--timeout=$RDUEVENT_TIMEOUT} \
		    --basedir "$eventdir" \
		    --rulesdir "$handlerdir" \
		    --pidfile "$PIDFILE" \
		    --logfile "/var/log/$NAME.log" \
		    -L debug
	RETVAL=$?
	return $RETVAL
}

stop() {
	stop_daemon $ARGS -- "$NAME"
	RETVAL=$?
	return $RETVAL
}

switch "${1-}"
