#!/bin/sh

. /.initrd/initenv
. uevent-sh-functions

message_time=1

roflag=-w
[ -z "$READONLY" ] || roflag=-r

handler() {
	[ -d "$MOUNTPOINT" ] ||
		return 1
	mountpoint -q "$MOUNTPOINT" ||
		mount ${DEBUG:+-v} "$roflag" "$MOUNTPOINT" ||
		return 1
}

handler &&
	done_event "$BASEDIR/$QUEUE/$EVENTNAME" ||:
