#!/bin/sh

. uevent-sh-functions

message_time=1

handler() {
	if [ ! -e /sys/power/resume ]; then
		message "Kernel does not support resume - doing normal boot"
		return 0
	fi

	# hardcode path, uswsusp ships an resume binary too
	/bin/resume "$INIT_RESUME"
	return 0
}

handler ||:
done_event "$BASEDIR/$QUEUE/$EVENTNAME"
