#!/bin/sh -efux

hsh --init --excludedocs

hsh-install --excludedocs \
	gcc make git-core expect libkmod-devel zlib-devel bzlib-devel \
	liblzma-devel libzstd-devel libelf-devel \
	help2man tar cpio coreutils pciutils util-linux sfdisk rsync unzip wget \
	dmsetup lvm2 cryptsetup mdadm e2fsprogs btrfs-progs xfsprogs \
	bash fdisk strace gzip xz iproute2 chrooted-resolv sysvinit-utils \
	btrfs-progs dosfstools e2fsprogs jfsutils ntfs-3g reiserfsprogs \
	squashfs-tools xfsprogs \
	grub-efi grub-pc extlinux lilo \
	libtirpc-devel libcrypt-devel

#hsh-install --excludedocs make-initrd-busybox

cat >"$0.exec"<<EOF
#!/bin/sh -efu

find / \
	\( \
		   \! -path '/.*' \
		-a \! -path '/usr/lib/locale/*' \
		-a \! -path '/usr/share/locale/*' \
		-a \! -path '/usr/share/doc/*' \
		-a \! -path '/usr/share/man/*' \
		-a \! -path '/usr/share/info/*' \
		-a \! -path '/usr/share/icons/*' \
		-a \! -path '/usr/share/zsh/*' \
		-a \! -path '/lib/initrd/*' \
		-a \! -path '/usr/share/make-initrd/*' \
		-a \! -path '/rootfs.cpio' \
	\) \
	-print0 |
	cpio -H newc -ov0
EOF

hsh-run --root --execute="$0.exec" > "rootfs-altlinux-$(date +'%Y%m%d').cpio"
