KICKSTART_DIRS := $(shell $(FEATURESDIR)/kickstart/bin/get-ks-configs)

PUT_FEATURE_DIRS += $(KICKSTART_DATADIR) $(KICKSTART_DIRS)
PUT_FEATURE_PROGS += $(KICKSTART_PROGS)
PUT_FEATURE_PROGS_WILDCARD += $(KICKStART_PROGS_PATTERNS)
