#!/bin/sh -efu

. /.initrd/initenv
. uevent-sh-functions
. initrd-sh-functions

devresume=
get_dev devresume "${RESUME-}" ||
	exit 0
event="$(make_event)"
export INIT_RESUME="$devresume"
environ -q -i 'INIT_RESUME' > "$event"
release_event resume "$event"
