#!/bin/sh

. /.initrd/initenv
. uevent-sh-functions

handler() {
	. "/tmp/net-$INTERFACE.conf"

	# get nfs root from dhcp
	if [ "$NFSROOT" = 'auto' ]; then
		NFSROOT="$ROOTPATH"
		[ "${NFSROOT#*:}" != "$NFSROOT" ] || NFSROOT="$ROOTSERVER:$ROOTPATH"
	else
	# nfsroot=[<server-ip>:]<root-dir>[,<nfs-options>]
		[ "${NFSROOT#*,}" = "$NFSROOT" ] || NFSOPTS="-o ${NFSROOT#*,}"
		NFSROOT=${NFSROOT%%,*}
		[ "${NFSROOT#*:}" != "$NFSROOT" ] || NFSROOT="$ROOTSERVER:$NFSROOT"
	fi

	# nfs options are an optional arg
	[ -n "$NFSOPTS" ] || NFSOPTS="-o retrans=10"

	local roflag='-o rw'
	[ -z "$READONLY" ] || roflag='-o ro'

	mountpoint -q "$rootmnt" ||
		nfsmount -o nolock $roflag $NFSOPTS "$NFSROOT" "$rootmnt" ||
		return 1
}

handler ||:
done_event "$BASEDIR/$QUEUE/$EVENTNAME"
